def test_pdf_export_builds_valid_pdf_bilingual():
    from services.pdf_export import build_ra_pdf
    from services.pre_ra import build_default_sections

    report = {
        "Project": "地下室 R.C. Manhole 建造工程",
        "Report Language": "Traditional Chinese",
        "Generated By": "NVIDIA AI",
        "Confirmed Steps": ["清理施工範圍", "混凝土澆築"],
        "Statutory Extra": ["Cap. 59I 建築地盤(安全)規例"],
    }
    rows = [
        {
            "Work Step": "混凝土澆築", "Hazard": "觸電致命", "Persons at Risk": "工人",
            "Cause of Hazard": "電動工具漏電", "Possible Consequence": "觸電死亡",
            "Existing Controls": "RCD 保護", "Additional Controls Required": "每日檢查電纜",
            "Permit / Competent Person": "REW", "Responsible Person": "CP",
            "Initial Risk": "P3 x S5 = 15 HR", "Residual Risk": "P1 x S5 = 5 MR",
        },
    ]
    secs = build_default_sections({"flags": {}}, {"report_language": "Traditional Chinese", "activity": "混凝土井建造 切割", "confirmed_steps": ["澆築 模板"]})
    buf = build_ra_pdf(report, rows, {}, secs)
    assert buf.getvalue()[:4] == b"%PDF"


def test_pdf_export_handles_english_and_empty():
    from services.pdf_export import build_ra_pdf

    report = {"Project": "Test Works", "Report Language": "English", "Generated By": "Local template"}
    assert build_ra_pdf(report, [], {}, {}).getvalue()[:4] == b"%PDF"
