"""PDF export for the RA report.

Mirrors the Word layout (A3 landscape, coloured risk cells, bilingual
headings) so the download offers Word / Excel / PDF. Chinese renders via
reportlab's built-in CID fonts (no external font files needed): MSung-Light
for Traditional, STSong-Light for Simplified.
"""

from __future__ import annotations

import re
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A3, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from services.docx_export import (
    _EMERGENCY_FIELD_LABELS,
    _SECTION_TABLE_HEADERS,
    _extract_probability_impact,
    _extract_score,
    _labels,
    _risk_fill,
    _static,
)

_CJK_REGISTERED: set[str] = set()


def _cjk_font(language: str) -> str:
    name = "STSong-Light" if language == "Simplified Chinese" else "MSung-Light"
    if name not in _CJK_REGISTERED:
        pdfmetrics.registerFont(UnicodeCIDFont(name))
        _CJK_REGISTERED.add(name)
    return name


def _hex(color_hex: str) -> colors.Color:
    return colors.HexColor("#" + color_hex.lstrip("#"))


_HEADER_BG = _hex("1F4D78")
_HEADER_FG = colors.white
_GRID = _hex("9AA7B4")
_BAND = _hex("F2F6FA")
_ALERT = _hex("C00000")

_PLACEHOLDER_MARKERS = ("[To be completed by site team", "[由工地團隊填寫", "[由工地填寫")


def _residual_above_target(text: str) -> bool:
    match = re.search(r"=\s*\d+\s*(LR|MR|HR)", str(text or ""))
    return bool(match and match.group(1) in {"MR", "HR"})


def _is_placeholder(text: str) -> bool:
    return any(marker in str(text or "") for marker in _PLACEHOLDER_MARKERS)


def build_ra_pdf(
    report: dict[str, Any],
    ra_rows: list[dict[str, Any]],
    matrix: dict[str, Any] | None = None,
    sections: dict[str, Any] | None = None,
) -> BytesIO:
    language = str(report.get("Report Language", "English"))
    lbl = _labels(language)
    static = _static(language)
    font = _cjk_font(language)
    sections = sections or {}

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A3),
        leftMargin=10 * mm,
        rightMargin=10 * mm,
        topMargin=10 * mm,
        bottomMargin=12 * mm,
        title=str(report.get("Project", "Risk Assessment Report")),
    )

    styles = getSampleStyleSheet()
    body = ParagraphStyle("cjk-body", parent=styles["Normal"], fontName=font, fontSize=7.2, leading=9, alignment=TA_LEFT)
    cell = ParagraphStyle("cjk-cell", parent=body, fontSize=6.6, leading=8.2)
    cell_alert = ParagraphStyle("cjk-cell-alert", parent=cell, textColor=_ALERT)
    h1 = ParagraphStyle("cjk-h1", parent=styles["Heading1"], fontName=font, fontSize=15, leading=18, textColor=_hex("0B2545"))
    h2 = ParagraphStyle("cjk-h2", parent=styles["Heading2"], fontName=font, fontSize=11, leading=14, textColor=_hex("1F4D78"), spaceBefore=8, spaceAfter=4)
    note = ParagraphStyle("cjk-note", parent=body, fontSize=7.5, leading=10, textColor=_hex("475569"))

    flow: list[Any] = []

    def P(text: Any, style: ParagraphStyle = cell) -> Paragraph:
        safe = str("" if text is None else text).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        safe = safe.replace("\n", "<br/>")
        return Paragraph(safe or "-", style)

    # ---- Title + metadata ----
    flow.append(Paragraph(str(report.get("Project", "Risk Assessment Report")), h1))
    flow.append(Paragraph(lbl.get("title", "Risk Assessment Report"), note))
    flow.append(Spacer(1, 4))

    meta = [
        (lbl.get("project", "Report Title"), report.get("Project", "-")),
        (lbl.get("project_name", "Project Name"), report.get("Task Location", "-")),
        (lbl.get("scope", "Scope of Works"), report.get("Construction Activity", "-")),
        (lbl.get("ms_source", "Method Statement Source"), report.get("Method Statement Source", "-")),
        (lbl.get("generated_by", "Generated By"), report.get("Generated By", "-")),
        (lbl.get("risk_matrix", "Risk Matrix"), report.get("Risk Matrix", "-")),
        (lbl.get("assessment_date", "Assessment Date"), report.get("Assessment Date", "-")),
        (lbl.get("next_review", "Next Review Date"), report.get("Next Review Date", "-")),
    ]
    meta_tbl = Table(
        [[P(k, cell), P(v, cell)] for k, v in meta],
        colWidths=[70 * mm, 320 * mm],
    )
    meta_tbl.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, _GRID),
        ("BACKGROUND", (0, 0), (0, -1), _BAND),
        ("FONTNAME", (0, 0), (-1, -1), font),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    flow.append(meta_tbl)

    # ---- Work sequence ----
    steps = report.get("Confirmed Steps") or []
    if steps:
        flow.append(Paragraph(lbl.get("sequence", "2.0 Work Method / Sequence"), h2))
        for idx, step in enumerate(steps, start=1):
            flow.append(P(f"{idx}. {step}", body))

    # ---- Statutory ----
    statutory = report.get("Statutory Extra") or []
    if statutory:
        flow.append(Paragraph(lbl.get("requirements", "3.0 Applicable Legislation / Site Requirements"), h2))
        for item in statutory:
            flow.append(P(f"• {item}", body))

    # ---- RA table ----
    flow.append(Paragraph(lbl.get("ra_table", "5.0 Hazard Identification & Risk Assessment"), h2))
    headers = [
        lbl.get("item", "Item"), lbl.get("job_task", "Job Task"), lbl.get("hazard", "Hazard"),
        lbl.get("people", "Persons"), lbl.get("cause", "Cause"), lbl.get("harm", "Consequence"),
        lbl.get("existing", "Existing Controls"), "P", "IC", lbl.get("risk_level", "RL"),
        lbl.get("further", "Further Controls"), lbl.get("training_ppe", "Training / PPE"),
        lbl.get("action_by", "By"), lbl.get("residual", "Residual"), lbl.get("actual", "Actual"),
    ]
    header_style = ParagraphStyle("hdr", parent=cell, fontName=font, fontSize=6.8, textColor=_HEADER_FG, alignment=1)
    data: list[list[Any]] = [[Paragraph(str(h), header_style) for h in headers]]
    style_cmds: list[tuple] = [
        ("GRID", (0, 0), (-1, -1), 0.5, _GRID),
        ("BACKGROUND", (0, 0), (-1, 0), _HEADER_BG),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 1.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 2),
        ("RIGHTPADDING", (0, 0), (-1, -1), 2),
        ("ALIGN", (7, 1), (9, -1), "CENTER"),
        ("ALIGN", (13, 1), (14, -1), "CENTER"),
    ]

    for i, row in enumerate(ra_rows, start=1):
        p_val, ic_val = _extract_probability_impact(row.get("Initial Risk"))
        initial_score = _extract_score(row.get("Initial Risk"))
        residual_text = str(row.get("Residual Risk") or "")
        residual_score = _extract_score(residual_text)
        residual_alert = _residual_above_target(residual_text)
        residual_style = cell_alert if residual_alert else cell
        data.append([
            P(i, cell), P(row.get("Work Step") or "To be confirmed"), P(row.get("Hazard")),
            P(row.get("Persons at Risk") or row.get("Persons")), P(row.get("Cause of Hazard")),
            P(row.get("Possible Consequence")), P(row.get("Existing Controls")),
            P(p_val), P(ic_val), P(row.get("Initial Risk")),
            P(row.get("Additional Controls Required")), P(row.get("Permit / Competent Person") or row.get("Training / PPE")),
            P(row.get("Responsible Person")), P(residual_text, residual_style),
            P(f"{residual_score or '-'}", residual_style),
        ])
        if initial_score is not None:
            fill = _hex(_risk_fill(initial_score))
            for col in (7, 8, 9):
                style_cmds.append(("BACKGROUND", (col, i), (col, i), fill))
        if residual_score is not None:
            fill = _hex(_risk_fill(residual_score))
            for col in (13, 14):
                style_cmds.append(("BACKGROUND", (col, i), (col, i), fill))
        if i % 2 == 0:
            style_cmds.append(("BACKGROUND", (1, i), (6, i), _BAND))
            style_cmds.append(("BACKGROUND", (10, i), (12, i), _BAND))

    # 15 columns tuned to the A3 landscape text width (~397mm usable).
    col_widths = [10, 34, 34, 22, 32, 30, 42, 9, 9, 20, 42, 34, 22, 22, 15]
    col_widths = [w * mm for w in col_widths]
    ra_tbl = Table(data, colWidths=col_widths, repeatRows=1)
    ra_tbl.setStyle(TableStyle(style_cmds))
    flow.append(ra_tbl)
    flow.append(Spacer(1, 3))
    flow.append(Paragraph(static.get("minimum_acceptable_risk", ""), note))

    # ---- Supporting sections ----
    def section_table(kind: str, rows: list[dict[str, Any]], keys: list[str], widths: list[float]) -> None:
        header = _SECTION_TABLE_HEADERS[kind].get(language, _SECTION_TABLE_HEADERS[kind]["English"])
        hstyle = ParagraphStyle("sh", parent=cell, fontName=font, fontSize=7, textColor=_HEADER_FG, alignment=1)
        tdata = [[Paragraph(str(h), hstyle) for h in header]]
        cmds = [
            ("GRID", (0, 0), (-1, -1), 0.5, _GRID),
            ("BACKGROUND", (0, 0), (-1, 0), _HEADER_BG),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 2), ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ]
        for ri, row in enumerate(rows, start=1):
            tdata.append([P(row.get(k)) for k in keys])
            if ri % 2 == 0:
                cmds.append(("BACKGROUND", (0, ri), (-1, ri), _BAND))
        tbl = Table(tdata, colWidths=[w * mm for w in widths], repeatRows=1)
        tbl.setStyle(TableStyle(cmds))
        flow.append(tbl)

    ppe = sections.get("ppe_by_trade") or []
    if ppe:
        flow.append(Paragraph(lbl.get("ppe", "6.0 PPE Requirements"), h2))
        for item in ppe:
            flow.append(P(f"• {item}", body))

    permits = sections.get("permits_checklist") or []
    if permits:
        flow.append(Paragraph(lbl.get("permits", "7.0 Permits & Statutory Documentation"), h2))
        section_table("permits", permits,
                      ["permit_or_form", "category", "legal_basis_or_sms_ref", "issued_by", "validity", "status"],
                      [70, 30, 90, 55, 45, 40])

    emergency = sections.get("emergency_arrangements") or {}
    if any(emergency.get(k) for k in _EMERGENCY_FIELD_LABELS["English"]):
        flow.append(Paragraph(lbl.get("emergency", "8.0 Emergency Arrangements"), h2))
        field_labels = _EMERGENCY_FIELD_LABELS.get(language, _EMERGENCY_FIELD_LABELS["English"])
        for sc in emergency.get("foreseeable_scenarios") or []:
            flow.append(P(f"• {sc}", body))
        for key in ("rescue_plan", "first_aid", "emergency_contacts", "assembly_point", "adverse_weather_arrangements"):
            value = emergency.get(key)
            if value:
                style = cell_alert if _is_placeholder(str(value)) else body
                flow.append(Paragraph(f"<b>{field_labels[key]}:</b> {str(value)}".replace("&", "&amp;"), style))

    training = sections.get("training_records") or []
    if training:
        flow.append(Paragraph(lbl.get("training", "9.0 Training & Competency Records"), h2))
        section_table("training", training,
                      ["role", "required_training_certificate", "legal_basis", "expiry_renewal", "record_location"],
                      [55, 110, 75, 45, 45])

    schedule = sections.get("inspection_schedule") or []
    if schedule:
        flow.append(Paragraph(lbl.get("monitoring", "10.0 Monitoring & Inspection Schedule"), h2))
        section_table("monitoring", schedule,
                      ["item", "frequency", "by_whom", "record_form"],
                      [120, 90, 60, 60])

    # ---- Approval ----
    flow.append(Paragraph(lbl.get("approval", "12.0 Approval / Acknowledgement"), h2))
    approval_header = [lbl.get("role", "Role"), lbl.get("position", "Position"), lbl.get("name", "Name"), lbl.get("signature", "Signature"), lbl.get("date", "Date")]
    if language in {"Traditional Chinese", "Simplified Chinese"}:
        approval_body = [
            ["編製", "安全顧問 / 安全主任"], ["審閱", "項目經理"], ["審閱", "工地監督 / 工頭"],
            ["確認", "分判商代表"], ["核實", "合資格人士"], ["確認", "客戶代表（如需要）"],
        ]
    else:
        approval_body = [
            ["Prepared by", "Safety Consultant / Safety Officer"], ["Reviewed by", "Project Manager"],
            ["Reviewed by", "Site Supervisor / Foreman"], ["Acknowledged by", "Subcontractor Representative"],
            ["Verified by", "Competent Person"], ["Acknowledged by", "Client Representative (if required)"],
        ]
    ahstyle = ParagraphStyle("ah", parent=cell, fontName=font, fontSize=8, textColor=_HEADER_FG, alignment=1)
    adata = [[Paragraph(str(h), ahstyle) for h in approval_header]]
    for role, position in approval_body:
        adata.append([P(role, body), P(position, body), P(""), P(""), P("")])
    atbl = Table(adata, colWidths=[40 * mm, 80 * mm, 70 * mm, 70 * mm, 40 * mm], repeatRows=1)
    atbl.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.6, colors.black),
        ("BACKGROUND", (0, 0), (-1, 0), _hex("FFF44F")),
        ("BACKGROUND", (0, 1), (0, -1), _BAND),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    flow.append(KeepTogether(atbl))

    doc.build(flow)
    buffer.seek(0)
    return buffer
