from __future__ import annotations

from typing import Literal, get_origin
from pydantic import BaseModel, Field, model_validator


class NoneTolerantModel(BaseModel):
    """AI backends return null for unknown fields; treat null as 'use default'
    instead of failing validation and discarding the whole response. Also
    coerces shape mismatches (a list where a string is expected and vice
    versa) — e.g. Gemini returns plant_equipment as a list, which previously
    failed validation and threw away the entire extraction."""

    @model_validator(mode="before")
    @classmethod
    def _drop_nulls(cls, data):
        if not isinstance(data, dict):
            return data
        cleaned = {}
        for key, value in data.items():
            if value is None:
                continue
            if isinstance(value, list):
                value = [item for item in value if item is not None]
            field = cls.model_fields.get(key)
            if field is not None:
                annotation = field.annotation
                if annotation is str:
                    if isinstance(value, list):
                        value = "; ".join(str(item).strip() for item in value if str(item).strip())
                    elif not isinstance(value, str):
                        value = str(value)
                elif get_origin(annotation) is list and isinstance(value, str):
                    value = [value] if value.strip() else []
            cleaned[key] = value
        return cleaned


class RAItem(NoneTolerantModel):
    source_step_id: str = ""
    source_step_text_original: str = ""
    source_step_text_translated: str = ""
    hazard_id: str = ""
    hazard_category: str = ""
    work_step: str = "To be confirmed"
    hazard: str = "To be confirmed"
    cause_of_hazard: str = "To be confirmed"
    possible_consequence: str = "To be confirmed"
    persons_at_risk: str = "Workers / others nearby"
    initial_risk_rating: str = "To be confirmed"
    existing_control_measures: str = "To be confirmed"
    additional_control_measures_required: str = "To be confirmed"
    residual_risk_rating: str = "To be confirmed"
    legal_cop_reference: str = "To be verified by Safety Officer"
    permit_certificate_competent_person_required: str = "To be confirmed"
    inspection_monitoring_points: str = "To be confirmed"
    responsible_person: str = "To be confirmed"
    remarks_items_to_be_confirmed: str = "To be confirmed"


class PermitChecklistRow(NoneTolerantModel):
    permit_or_form: str = ""
    category: str = ""  # "Statutory" or "In-house"
    legal_basis_or_sms_ref: str = ""
    issued_by: str = ""
    validity: str = ""
    status: str = "To be confirmed"


class TrainingRecordRow(NoneTolerantModel):
    role: str = ""
    required_training_certificate: str = ""
    legal_basis: str = ""
    expiry_renewal: str = ""
    record_location: str = ""


class InspectionScheduleRow(NoneTolerantModel):
    item: str = ""
    frequency: str = ""
    by_whom: str = ""
    record_form: str = ""


class EmergencyArrangements(NoneTolerantModel):
    foreseeable_scenarios: list[str] = Field(default_factory=list)
    rescue_plan: str = ""
    first_aid: str = ""
    emergency_contacts: str = ""
    assembly_point: str = ""
    adverse_weather_arrangements: str = ""


class RADraft(NoneTolerantModel):
    disclaimer: str
    overall_risk_level: str = "To be confirmed"
    items: list[RAItem] = Field(default_factory=list)
    # Supporting sections (optional; generated by the AI path)
    ppe_by_trade: list[str] = Field(default_factory=list)
    permits_checklist: list[PermitChecklistRow] = Field(default_factory=list)
    emergency_arrangements: EmergencyArrangements | None = None
    training_records: list[TrainingRecordRow] = Field(default_factory=list)
    inspection_schedule: list[InspectionScheduleRow] = Field(default_factory=list)


class MethodStatementExtraction(NoneTolerantModel):
    document_title: str = "To be confirmed"
    construction_activity: str = "To be confirmed"
    project_name: str = "To be confirmed"
    work_steps: list[str] = Field(default_factory=list)
    rejected_headings_or_controls: list[str] = Field(default_factory=list)
    # Document extraction mode: pull supporting details when stated in the MS.
    plant_equipment: str = ""
    workforce_trades: str = ""
    working_height_environment: str = ""
    duration_time_of_work: str = ""
    existing_safety_provisions: list[str] = Field(default_factory=list)
    permits_certificates_mentioned: str = ""
    ppe_mentioned: str = ""
    extraction_notes: str = ""


class InspectionDraft(BaseModel):
    disclaimer: str
    formal_finding_en: str
    formal_finding_zh: str
    risk_possible_consequence: str
    immediate_action: str
    corrective_action: str
    preventive_action: str
    legal_cop_reference_tag: str = "To be verified by Safety Officer"
    follow_up_checking_point: str
    status: str = "Open"


class IncidentDraft(BaseModel):
    disclaimer: str
    internal_accident_report_draft: str
    accident_chronology: list[str] = Field(default_factory=list)
    immediate_causes: list[str] = Field(default_factory=list)
    root_cause_analysis: list[str] = Field(default_factory=list)
    corrective_preventive_action_table: list[dict[str, str]] = Field(default_factory=list)
    evidence_checklist: list[str] = Field(default_factory=list)
    statutory_reporting_checklist: list[str] = Field(default_factory=list)
    items_to_be_verified_by_safety_officer: list[str] = Field(default_factory=list)
    privacy_warning: str = ""


class CheckerDraft(BaseModel):
    result: Literal["PASS FOR SO REVIEW", "REVISE REQUIRED", "CRITICAL MISSING ITEM", "LEGAL REFERENCE TO BE VERIFIED"]
    comments: list[str] = Field(default_factory=list)
    suggested_revised_wording: list[str] = Field(default_factory=list)
